spring:
  datasource:
    url: jdbc:postgresql://postgres_prod_db:5432/minane_prod?connectTimeout=5000&socketTimeout=5000
    username: prod_user
    password: ProdPassword2024!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# Upload directory for PRODUCTION on Linux
app:
  upload:
    dir: /var/www/uploads

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
