spring:
  datasource:
    url: jdbc:postgresql://postgres_test_db:5432/minane_test
    username: test_user
    password: TestPassword2024!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true