spring:
  datasource:
    url: jdbc:postgresql://postgres_test_db:5432/minane_test?connectTimeout=5000&socketTimeout=5000
    username: test_user
    password: TestPassword2024!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# Upload directory for LOCAL
app:
  upload:
    dir: C:/uploads

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
