server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://postgres_prod_db:5432/minane_prod
    username: prod_user
    password: ProdPassword2024!

  jpa:
    hibernate:
      ddl-auto: update   # ⚡ Crée ou met à jour les tables si nécessaire
    show-sql: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

app:
  upload:
    dir: ${APP_UPLOAD_DIR:/app/uploads}

logging:
  pattern:
    console: "%red([PROD]) %d{yyyy-MM-dd HH:mm:ss} %-5level %logger - %msg%n"
